import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '@mui/material/Button';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio Professional</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="contained"> Olá Mundo</Button>;
    </div>
  )
}

export default Home
